services:
  - type: web
    name: mvp-dental-backend
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: GO_ENV
        value: production
      - key: PORT
        value: 8080
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    plan: free
    numInstances: 1
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 